version: '3.4'

x-common-variables: &common-variables
  HSELING_RPC_ENDPOINT: http://hse-api-web:80/rpc/
  HSELING_API_ENDPOINT: http://hse-api-web:80/api/
  RESTRICTED_MODE: 0

services:
  hse-api-web:
    build:
      context: .
      dockerfile: hseling-api-iceform/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - type: bind
        source: ./hseling-api-iceform/hseling_api_iceform
        target: /app/hseling_api_iceform
      - type: bind
        source: ./hseling-data-iceform/api
        target: /data
    environment: *common-variables






  hse-web-web:
    build:
      context: .
      dockerfile: hseling-web-iceform/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - hse-api-web
    environment: *common-variables
    volumes:
      - type: bind
        source: ./hseling-web-iceform/hseling_web_iceform
        target: /app/hseling_web_iceform
      - type: bind
        source: ./hseling-web-iceform/hseling_web_iceform/static
        target: /app/static
      - type: bind
        source: ./hseling-data-iceform/web
        target: /data
